name: flutter_quran
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  hijri: ^3.0.0
  flutter_qiblah: ^3.1.0+1
  adhan_dart: ^1.1.2
  geolocator: ^13.0.2
  provider: ^6.1.2
  azlistview: ^2.0.0
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logoText.png
    - assets/images/bismillah.png
    - assets/images/ayatNumber.png
    - assets/json/surah.json
    - assets/json/doa.json
    - assets/json/surah/1.json
    - assets/json/surah/2.json
    - assets/json/surah/3.json
    - assets/json/surah/4.json
    - assets/json/surah/5.json
    - assets/json/surah/6.json
    - assets/json/surah/7.json
    - assets/json/surah/8.json
    - assets/json/surah/9.json
    - assets/json/surah/10.json
    - assets/json/surah/11.json
    - assets/json/surah/12.json
    - assets/json/surah/13.json
    - assets/json/surah/14.json
    - assets/json/surah/15.json
    - assets/json/surah/16.json
    - assets/json/surah/17.json
    - assets/json/surah/18.json
    - assets/json/surah/19.json
    - assets/json/surah/20.json
    - assets/json/surah/21.json
    - assets/json/surah/22.json
    - assets/json/surah/23.json
    - assets/json/surah/24.json
    - assets/json/surah/25.json
    - assets/json/surah/26.json
    - assets/json/surah/27.json
    - assets/json/surah/28.json
    - assets/json/surah/29.json
    - assets/json/surah/30.json
    - assets/json/surah/31.json
    - assets/json/surah/32.json
    - assets/json/surah/33.json
    - assets/json/surah/34.json
    - assets/json/surah/35.json
    - assets/json/surah/36.json
    - assets/json/surah/37.json
    - assets/json/surah/38.json
    - assets/json/surah/39.json
    - assets/json/surah/40.json
    - assets/json/surah/41.json
    - assets/json/surah/42.json
    - assets/json/surah/43.json
    - assets/json/surah/44.json
    - assets/json/surah/45.json
    - assets/json/surah/46.json
    - assets/json/surah/47.json
    - assets/json/surah/48.json
    - assets/json/surah/49.json
    - assets/json/surah/50.json
    - assets/json/surah/51.json
    - assets/json/surah/52.json
    - assets/json/surah/53.json
    - assets/json/surah/54.json
    - assets/json/surah/55.json
    - assets/json/surah/56.json
    - assets/json/surah/57.json
    - assets/json/surah/58.json
    - assets/json/surah/59.json
    - assets/json/surah/60.json
    - assets/json/surah/61.json
    - assets/json/surah/62.json
    - assets/json/surah/63.json
    - assets/json/surah/64.json
    - assets/json/surah/65.json
    - assets/json/surah/66.json
    - assets/json/surah/67.json
    - assets/json/surah/68.json
    - assets/json/surah/69.json
    - assets/json/surah/70.json
    - assets/json/surah/71.json
    - assets/json/surah/72.json
    - assets/json/surah/73.json
    - assets/json/surah/74.json
    - assets/json/surah/75.json
    - assets/json/surah/76.json
    - assets/json/surah/77.json
    - assets/json/surah/78.json
    - assets/json/surah/79.json
    - assets/json/surah/80.json
    - assets/json/surah/81.json
    - assets/json/surah/82.json
    - assets/json/surah/83.json
    - assets/json/surah/84.json
    - assets/json/surah/85.json
    - assets/json/surah/86.json
    - assets/json/surah/87.json
    - assets/json/surah/88.json
    - assets/json/surah/89.json
    - assets/json/surah/90.json
    - assets/json/surah/91.json
    - assets/json/surah/92.json
    - assets/json/surah/93.json
    - assets/json/surah/94.json
    - assets/json/surah/95.json
    - assets/json/surah/96.json
    - assets/json/surah/97.json
    - assets/json/surah/98.json
    - assets/json/surah/99.json
    - assets/json/surah/100.json
    - assets/json/surah/101.json
    - assets/json/surah/102.json
    - assets/json/surah/103.json
    - assets/json/surah/104.json
    - assets/json/surah/105.json
    - assets/json/surah/106.json
    - assets/json/surah/107.json
    - assets/json/surah/108.json
    - assets/json/surah/109.json
    - assets/json/surah/110.json
    - assets/json/surah/111.json
    - assets/json/surah/112.json
    - assets/json/surah/113.json
    - assets/json/surah/114.json
    - assets/json/tafsir/1.json
    - assets/json/tafsir/2.json
    - assets/json/tafsir/3.json
    - assets/json/tafsir/4.json
    - assets/json/tafsir/5.json
    - assets/json/tafsir/6.json
    - assets/json/tafsir/7.json
    - assets/json/tafsir/8.json
    - assets/json/tafsir/9.json
    - assets/json/tafsir/10.json
    - assets/json/tafsir/11.json
    - assets/json/tafsir/12.json
    - assets/json/tafsir/13.json
    - assets/json/tafsir/14.json
    - assets/json/tafsir/15.json
    - assets/json/tafsir/16.json
    - assets/json/tafsir/17.json
    - assets/json/tafsir/18.json
    - assets/json/tafsir/19.json
    - assets/json/tafsir/20.json
    - assets/json/tafsir/21.json
    - assets/json/tafsir/22.json
    - assets/json/tafsir/23.json
    - assets/json/tafsir/24.json
    - assets/json/tafsir/25.json
    - assets/json/tafsir/26.json
    - assets/json/tafsir/27.json
    - assets/json/tafsir/28.json
    - assets/json/tafsir/29.json
    - assets/json/tafsir/30.json
    - assets/json/tafsir/31.json
    - assets/json/tafsir/32.json
    - assets/json/tafsir/33.json
    - assets/json/tafsir/34.json
    - assets/json/tafsir/35.json
    - assets/json/tafsir/36.json
    - assets/json/tafsir/37.json
    - assets/json/tafsir/38.json
    - assets/json/tafsir/39.json
    - assets/json/tafsir/40.json
    - assets/json/tafsir/41.json
    - assets/json/tafsir/42.json
    - assets/json/tafsir/43.json
    - assets/json/tafsir/44.json
    - assets/json/tafsir/45.json
    - assets/json/tafsir/46.json
    - assets/json/tafsir/47.json
    - assets/json/tafsir/48.json
    - assets/json/tafsir/49.json
    - assets/json/tafsir/50.json
    - assets/json/tafsir/51.json
    - assets/json/tafsir/52.json
    - assets/json/tafsir/53.json
    - assets/json/tafsir/54.json
    - assets/json/tafsir/55.json
    - assets/json/tafsir/56.json
    - assets/json/tafsir/57.json
    - assets/json/tafsir/58.json
    - assets/json/tafsir/59.json
    - assets/json/tafsir/60.json
    - assets/json/tafsir/61.json
    - assets/json/tafsir/62.json
    - assets/json/tafsir/63.json
    - assets/json/tafsir/64.json
    - assets/json/tafsir/65.json
    - assets/json/tafsir/66.json
    - assets/json/tafsir/67.json
    - assets/json/tafsir/68.json
    - assets/json/tafsir/69.json
    - assets/json/tafsir/70.json
    - assets/json/tafsir/71.json
    - assets/json/tafsir/72.json
    - assets/json/tafsir/73.json
    - assets/json/tafsir/74.json
    - assets/json/tafsir/75.json
    - assets/json/tafsir/76.json
    - assets/json/tafsir/77.json
    - assets/json/tafsir/78.json
    - assets/json/tafsir/79.json
    - assets/json/tafsir/80.json
    - assets/json/tafsir/81.json
    - assets/json/tafsir/82.json
    - assets/json/tafsir/83.json
    - assets/json/tafsir/84.json
    - assets/json/tafsir/85.json
    - assets/json/tafsir/86.json
    - assets/json/tafsir/87.json
    - assets/json/tafsir/88.json
    - assets/json/tafsir/89.json
    - assets/json/tafsir/90.json
    - assets/json/tafsir/91.json
    - assets/json/tafsir/92.json
    - assets/json/tafsir/93.json
    - assets/json/tafsir/94.json
    - assets/json/tafsir/95.json
    - assets/json/tafsir/96.json
    - assets/json/tafsir/97.json
    - assets/json/tafsir/98.json
    - assets/json/tafsir/99.json
    - assets/json/tafsir/100.json
    - assets/json/tafsir/101.json
    - assets/json/tafsir/102.json
    - assets/json/tafsir/103.json
    - assets/json/tafsir/104.json
    - assets/json/tafsir/105.json
    - assets/json/tafsir/106.json
    - assets/json/tafsir/107.json
    - assets/json/tafsir/108.json
    - assets/json/tafsir/109.json
    - assets/json/tafsir/110.json
    - assets/json/tafsir/111.json
    - assets/json/tafsir/112.json
    - assets/json/tafsir/113.json
    - assets/json/tafsir/114.json

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
